language: python
python:
  - "2.7"
  - "pypy"
install:
  - pip --default-timeout=180 install -r requirements.txt --use-mirrors
  - pip --default-timeout=180 install -r test_requirements.txt --use-mirrors
  - 'if [[ "$TRAVIS_PYTHON_VERSION" != "pypy" ]]; then pip install psycopg2 --use-mirrors; fi'
before_script:
  - psql -c 'create database lastuser_test_app;' -U postgres
script:
  - 'if [[ "$TRAVIS_PYTHON_VERSION" != "pypy" ]]; then nosetests ; fi'
  - 'if [[ "$TRAVIS_PYTHON_VERSION" == "pypy" ]]; then SQLALCHEMY_DATABASE_URI="sqlite://" nosetests ; fi'
notifications:
  email: false
  irc: "irc.freenode.net#hasgeek-dev"
